#!/usr/bin/env perl

use v5.20;

use strict;
use warnings;

use Mojolicious::Lite;
use Mojo::JWT;
use DBI;

plugin JSONConfig => { file => app->home->rel_file( 'conf/talk_history.json' ) };

get '/' => sub {
    my $c = shift;

    my $session_ok = $c->check_session;

    my $target = $session_ok ? '/login' : '/events';
    return $c->redirect_to( $c->url_for($target) );
};

get '/login' => 'login';

post '/login' => sub {
    my $c = shift;

    my $login = $c->login;
    my $target = $login ? '/events' : '/login';

    return $c->redirect_to( $c->url_for( $target ) );
};

under '/' => sub {
    my ($c) = shift;

    my $session_ok = $c->check_session;

    my $target = $session_ok ? '/login' : '/events';
    return $target;
};

get '/events'                => 'events';
get '/talks'                 => 'talks';
get '/event/:id'             => 'event';
get '/event/:event_id/talks' => 'talks';
get '/talk/:talk_id'         => 'talk';


post '/events/new' => sub {
    my $c = shift;

    # validate user input

    my $uuid = $c->save_event;
};

post '/events/:id/talks/new' => sub {
};

